#!/bin/bash

echo ""
echo ""
echo "Note: this script is to create a backup of the Mediaflux database file. It simply copy & compress the database file \$MFLUX_HOME/volatile/databases/MFLUXDB.db to the backup directory. You need to export the environment variable: MFLUX_HOME and MFLUX_BACKUP_DIR to the correct locations."
echo ""
echo ""

# check if mfexec script exists
MFEXEC=`dirname $0`/mf_exec
if [[ ! -e $MFEXEC ]]; then
	echo "Error: cannot find $MFEXEC"
	exit 1
fi
if [[ ! -x $MFEXEC ]]; then
	echo "Error: $MFEXEC is not excutable. try \"chmod +x ${MFEXEC}\""
	exit 1
fi

# check if tar exists
if [[ -z `which tar` ]]; then
	echo "Error: cannot find tar."
	exit 1
fi

# check if gzip exists
if [[ -z `which gzip` ]]; then
	echo "Error: cannot find gzip."
	exit 1
fi

# check if MFLUX_HOME is set
if [[ -z $MFLUX_HOME ]]; then
	echo "Error: MFLUX_HOME is not set."
	exit 1
fi

MFLUX_DB_FILE=$MFLUX_HOME/volatile/databases/MFLUXDB.db

# check if MFLUX_DB_FILE exists
if [[ ! -f $MFLUX_DB_FILE ]]; then
	echo "Error: cannot find Meidaflux database file: $MFLUX_DB_FILE."
	exit 1
fi


# MFLUX_BACKUP_DIR
if [[ ! -z $1 ]]; then
	if [[ -d $1 ]]; then
		MFLUX_BACKUP_DIR=$1
	else
		echo "Error: $1 is not a directory"
		exit 1
	fi
else
	if [[ -z $MFLUX_BACKUP_DIR ]]; then
		echo "Error: no MFLUX_BACKUP_DIR is set. you can either \"export MFLUX_BACKUP_DIR=/path/to/backup_dir; `basename $0`\" or \"`basename $0` /path/to/backup_dir\""
		exit 1
	fi
fi

# MFLUX_DB_BACKUP_FILE
MFLUX_DB_BACKUP_FILE=$MFLUX_BACKUP_DIR/MFLUXDB.db.tar.gz

# Remove old backup
rm $MFLUX_DB_BACKUP_FILE

# Create new backup
tar czvf $MFLUX_DB_BACKUP_FILE	$MFLUX_DB_FILE

